export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_REQUEST_SUCCESS = "ADMIN_PRODUCT_REQUEST_SUCCESS";
export const ADMIN_PRODUCT_REQUEST_FAIL = "ADMIN_PRODUCT_REQUEST_FAIL";

export const ADMIN_USERS_REQUEST = "ADMIN_USERS_REQUEST";
export const ADMIN_USERS_REQUEST_SUCCESS = "ADMIN_USERS_REQUEST_SUCCESS";
export const ADMIN_USERS_REQUEST_FAIL = "ADMIN_USERS_REQUEST_FAIL";

export const ISADMIN_REQUEST = "ISADMIN_REQUEST";
export const ISADMIN_REQUEST_SUCCESS = "ISADMIN_REQUEST_SUCCESS";
export const ISADMIN_REQUEST_FAIL = "ISADMIN_REQUEST_FAIL";

export const ISACTIVE_REQUEST = "ISACTIVE_REQUEST";
export const ISACTIVE_REQUEST_SUCCESS = "ISACTIVE_REQUEST_SUCCESS";
export const ISACTIVE_REQUEST_FAIL = "ISACTIVE_REQUEST_FAIL";
