export const ORDER_REQUEST = "ORDER_REQUEST";
export const ORDER_REQUEST_SUCCESS = "ORDER_REQUEST_SUCCESS";
export const ORDER_REQUEST_FAIL = "ORDER_REQUEST_FAIL";

export const ORDER_HISTORY_REQUEST = "ORDER_HISTORY_REQUEST";
export const ORDER_HISTORY_REQUEST_SUCCESS = "ORDER_HISTORY_REQUEST_SUCCESS";
export const ORDER_HISTORY_REQUEST_FAIL = "ORDER_HISTORY_REQUEST_FAIL";

export const UPDATE_STATUS_REQUEST = "UPDATE_STATUS_REQUEST";
export const UPDATE_STATUS_REQUEST_SUCCESS = "UPDATE_STATUS_REQUEST_SUCCESS";
export const UPDATE_STATUS_REQUEST_FAIL = "UPDATE_STATUS_REQUEST_FAIL";

export const GET_MY_ORDERS_REQUEST = "GET_MY_ORDERS_REQUEST";
export const GET_MY_ORDERS_SUCCESS = "GET_MY_ORDERS_SUCCESS";
export const GET_MY_ORDERS_FAIL = "GET_MY_ORDERS_FAIL";


export const ORDER_REMOVE_PLACEDORDER = "ORDER_REMOVE_PLACEDORDER";
